import { StyleSheet } from "react-native"
import { Dimensions } from 'react-native';

let backgroundColor="#faf5ef";
let highlight="#63ba83";
let midtone = "#4ea66d";
let dark="#343434";
let warning = "#E07A5F";
let textColor=dark;
let darkTextColor=backgroundColor;

let pink="#c740d6";
let red="#d64040";
let yellow="#d6b640";
let green="#4ea66d";
let blue="#438ab0";
let teal="#43b0a9";
let indigo="#6243b0"

let largeFontSize = 20;
let mediumFontSize = 25;
let smallFontSize = 20;
let tinyFontSize = 18;
let baseWidth = Dimensions.get("window").width;
let baseHeight = Dimensions.get("window").height;

let minorFont='Gogh-ExtraBold';
let majorFont='goodlight';

//stylesheet, light mode
export default StyleSheet.create({
    container: {
        flex: 1,
        padding: Dimensions.get("window").width*.05,
        backgroundColor: backgroundColor,
    },
    buttonBox: {
        flex: 1,
        paddingHorizontal: Dimensions.get("window").width*.15,
        backgroundColor: backgroundColor,
    },
    bottomLine:{
        borderBottomColor: textColor,
        borderBottomWidth: 3,
    },
    background:{
        flex: 1,
        backgroundColor: backgroundColor,
    },
    title: {
        alignItems: 'center',
        color: textColor,
        textAlign: "center",
        fontSize: largeFontSize,
        fontFamily: majorFont,
        letterSpacing:3,
        flexWrap:'wrap',
        overflow: 'visible', 
        borderBottomColor: textColor,
        borderBottomWidth: 5,
    },
    header:{
        color: textColor,
        textAlign: "center",
        fontSize: mediumFontSize,
        margin:10,
        fontFamily: majorFont,
        flexWrap:'wrap',
        position:'relative',
        overflow: 'visible', 
    },
    subheader:{
        color: dark,
        textAlign: "center",
        fontSize: smallFontSize,
        margin:5,
        fontFamily: majorFont,
        flexWrap:'wrap',
        position:'relative',
        overflow: 'visible', 
    },
    regularText:{
        alignItems: 'center',
        color: dark,
        textAlign: "center",
        fontSize: smallFontSize,
        fontFamily: minorFont,
        flexWrap:'wrap',
        overflow: 'visible', 
    },
    fixToText: {
        flexDirection: 'row',
        flex:2,
        margin: 10,
        justifyContent: 'space-between',
        alignItems: 'center',
        flexWrap: "wrap",
    },
    input:{
        marginBottom:10,
        borderWidth:4,
        color: textColor,
        borderColor:highlight,
        textAlign: "center",
        borderRadius:15,
        fontSize: smallFontSize,
        overflow: 'hidden',
        fontFamily: minorFont,
        flexWrap:'wrap',
    },
    button: {
        alignItems: 'center',
        backgroundColor: midtone,
        color: darkTextColor,
        textAlign: "center",
        fontSize: mediumFontSize,
        borderRadius:15,
        padding:5,
        margin: 10,
        borderColor:midtone,
        paddingHorizontal:10,
        fontFamily: minorFont,
        flexWrap:'wrap',
        overflow: 'hidden', 
    },
    smallButton: {
        alignItems: 'center',
        backgroundColor: midtone,
        color: darkTextColor,
        textAlign: "center",
        fontSize: tinyFontSize,
        borderRadius:15,
        margin:5,
        padding:5,
        borderWidth:1,
        borderColor:midtone,
        paddingHorizontal:10,
        fontFamily: minorFont,
        flexWrap:'wrap',
        overflow: 'hidden', 
    },
    warningButton:{
        alignItems: 'center',
        backgroundColor: warning,
        color: darkTextColor,
        textAlign: "center",
        fontSize: smallFontSize,
        borderRadius:15,
        padding:5,
        margin: 5,
        borderColor:warning,
        paddingHorizontal:10,
        fontFamily: minorFont,
        flexWrap:'wrap',
        overflow: 'hidden',
        
    },
    lightButton:{
        alignItems: 'center',
        backgroundColor: highlight,
        color: darkTextColor,
        textAlign: "center",
        fontSize: smallFontSize,
        borderRadius:15,
        padding:5,
        margin: 5,
        borderColor:highlight,
        paddingHorizontal:10,
        fontFamily: minorFont,
        flexWrap:'wrap',
        overflow: 'hidden',
    },
    blueButton:{
        alignItems: 'center',
        backgroundColor: blue,
        color: darkTextColor,
        textAlign: "center",
        fontSize: smallFontSize,
        borderRadius:15,
        padding:5,
        margin: 5,
        borderColor:highlight,
        paddingHorizontal:10,
        fontFamily: minorFont,
        flexWrap:'wrap',
        overflow: 'hidden',
    },
    tableHead: {
        backgroundColor: highlight,
        flex: 1, 
        flexWrap: 'wrap',
        fontSize:smallFontSize,
        fontFamily: minorFont,
        textAlign: "center",
    },
    tableText: { 
       color: textColor,
       fontSize: tinyFontSize,
       margin: 6,
       fontFamily: minorFont,
       textAlign: "center",
       flex: 1, 
       flexWrap: 'wrap',
    },
    border:{
        borderWidth:10,
        borderColor:highlight,
        alignItems: 'center',
        backgroundColor: backgroundColor,
    },
    scrollView: {
        flex: 1,
    },
    tinyLogo: {
        width: 320*1.2,
        height: 100*1.2,
        resizeMode: 'contain',
        alignSelf: 'center',
    },
    titleLogo:{
        width: 320/3,
        height: 100/3,
        resizeMode: 'contain',
        alignSelf: 'center',
    },
    picker:{ 
        backgroundColor: midtone, 
        color: backgroundColor, 
        fontFamily: minorFont, 
        fontSize:smallFontSize,
        borderRadius:15,
        overflow: 'hidden', 
        textAlign: "center",
        padding: 5,
        margin: 10,
    },
    alert:{
        color: textColor,
        textAlign: "center",
        fontFamily: majorFont,
        backgroundColor: backgroundColor,
    },
    taskItem:{
        color: textColor,
        fontSize: tinyFontSize,
        margin: 6,
        fontFamily: minorFont,
        alignItems: 'center',
    },
    taskTitle:{
        backgroundColor:highlight,
        padding: 10,
        elevation: 4,
        margin: 10,
        color: backgroundColor,
        fontSize: tinyFontSize,
        margin: 6,
        fontFamily: majorFont,
        letterSpacing:2,
    },
    deleteButton:{
        alignItems: 'center',
        backgroundColor: warning,
        color: darkTextColor,
        textAlign: "center",
        fontSize: tinyFontSize,
        borderRadius:15,
        borderWidth:1,
        borderColor:warning,
        paddingHorizontal:10,
        fontFamily: minorFont,
        flexWrap:'wrap',
        overflow: 'hidden', 
    },
    barLine:{
        borderBottomColor: textColor,
        borderBottomWidth: 3,
    },
    tinyText:{
        alignItems: 'center',
        color: textColor,
        textAlign: "center",
        fontSize: tinyFontSize,
        fontFamily: minorFont,
        flexWrap:'wrap',
        overflow: 'visible', 
    },
    timelineText:{
        color: textColor,
        textAlign: "left",
        fontSize: tinyFontSize,
        fontFamily: minorFont,
    },
    buttonTask:{
        backgroundColor: blue,
        borderRadius:15,
        margin: 5,
        color: darkTextColor,
    },
    smallLightText:{
        textAlign: "center",
        color: darkTextColor,
        fontSize: smallFontSize,
        paddingHorizontal:10,
        fontFamily: majorFont,
        flexWrap:'wrap',
        overflow: 'hidden',
    },
    tinyLightText:{
        textAlign: "center",
        color: darkTextColor,
        fontSize: tinyFontSize,
        paddingHorizontal:10,
        fontFamily: minorFont,
        flexWrap:'wrap',
        overflow: 'hidden',  
    },
    bigButton:{
        alignItems: 'center',
        backgroundColor: midtone,
        color: darkTextColor,
        textAlign: "center",
        fontSize: largeFontSize,
        borderRadius:25,
        padding:10,
        margin: 10,
        borderColor:midtone,
        paddingHorizontal:10,
        fontFamily: majorFont,
        flexWrap:'wrap',
        overflow: 'hidden', 
    },
    alertBody:{
        color: textColor,
        textAlign: "center",
        fontFamily: minorFont,
        fontSize:10,
        backgroundColor: backgroundColor,
        overflow: 'hidden', 
    },
    alertText:{
        color: textColor,
        textAlign: "center",
        fontFamily: majorFont,
        fontSize:tinyFontSize,
        backgroundColor: backgroundColor,
        overflow: 'hidden', 
    },
    bigBlueButton:{
        alignItems: 'center',
        backgroundColor: blue,
        color: darkTextColor,
        textAlign: "center",
        fontSize: mediumFontSize,
        borderRadius:25,
        padding:10,
        margin: 10,
        borderColor:midtone,
        paddingHorizontal:10,
        fontFamily: majorFont,
        flexWrap:'wrap',
        overflow: 'hidden', 
    },
    modalBox:{
        alignItems: 'center',
        flex: 1,
        width:Dimensions.get("window").width*.8,
        height:Dimensions.get("window").height*.6,
        padding: Dimensions.get("window").width*.05,
        backgroundColor: backgroundColor,
        borderColor:dark,
        borderWidth:5,
        borderRadius:15,
        position: 'absolute', 
        top: Dimensions.get("window").height*.2, 
        left: Dimensions.get("window").width*.1, 
    },
    dayInput:{
        width:Dimensions.get("window").width*.25,
        marginBottom:10,
        borderWidth:4,
        color: textColor,
        borderColor:highlight,
        textAlign: "center",
        borderRadius:15,
        fontSize: smallFontSize,
        overflow: 'hidden',
        fontFamily: minorFont,
        flexWrap:'wrap',
    },
    pickerDropdown:{
        backgroundColor: midtone, 
        color: backgroundColor, 
        fontFamily: minorFont, 
        fontSize:smallFontSize,
        borderRadius:15,
        overflow: 'hidden', 
        textAlign: "center",
        padding: 5,
        margin: 10,
    },
    headerIcon:{
        alignSelf:'center', 
        width: 30, 
        height: 30
    },
    graphIcon:{
        alignSelf:'center',
        width: baseWidth * (7.5/18), 
        height: (baseWidth * (7.5/18)) * (2/3),
    },
    
    graphIconBig:{
        alignSelf:'center',
        width: baseWidth * (11/16),
        height: (baseWidth * (11/16)) * (2/3),
    },
    backgroundImage:{
        alignSelf:'center',
        width: 380,
        height: 380,
    }
})


